In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
type(arr)

[1 2 3 4]
<class 'numpy.ndarray'>


numpy.ndarray

# 2D array

In [6]:
arr=np.array([[2,3,4,5],[4,5,1,8]])
print(arr)
type(arr)

[[2 3 4 5]
 [4 5 1 8]]


numpy.ndarray

# 3D array

In [7]:
arr = np.array ([[21,34,55],[56,74,83]],[[45,56,78],[86,90,56]]])
print(arr)

[[[21 34 55]
  [56 74 83]
  [99 43 23]]]


In [10]:
arr.ndim

3